### ISSUE TITLE
Wrap orphan HTTP spans

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-android#103]
OpenTelemetry does not differentiate between transactions and spans, however, has a `span.kind` (SERVER, CLIENT, PRODUCER, CONSUMER, INTERNAL) field that describes the semantics of a span. A relevant snippet from the [SpanKind specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind) is the following:

> In order for SpanKind to be meaningful, callers SHOULD arrange that a single Span does not serve more than one purpose. For example, a server-side span SHOULD NOT be used directly as the parent of another remote span. As a simple guideline, instrumentation should create a new Span prior to extracting and serializing the SpanContext for a remote call.

In the mobile instrumentation it's sometimes not possible to wrap outgoing HTTP spans into parent actions. This results in a trace that has **only one span** on the mobile app side (that is at the same time the root of the trace and an outgoing HTTP request span).

The APM server has a heuristic that decides whether a span needs to be mapped to an Elastic transaction or an Elastic span. Depending on which branch this decision takes, different object are created and also different metrics are derived (e.g. destination metrics vs. transaction metrics)

<img width="1584" alt="image" src="https://user-images.githubusercontent.com/866830/205848390-cc971eed-5630-4b85-879e-53eaf00fa7e2.png">

For the above-described scenario the single span is mapped to a transaction (because it does not have a parent/ is a root span). Thus, we get a transaction document and that span contributes to the transaction metrics. However, that span does not contribute to destination metrics, and any other span-specific processing is not applied.

In that case we would need both, the characteristics of a transaction and an exit span to not break / impact existing features and to enable corresponding mobile features (e.g. properly counting and showing request statistics, counting sessions on transactions, properly displaying dependencies and the service map, etc.).

The following processing steps are required for the single span:

- from the transaction translation branch:
   - ALL of the metadata (`host`, `host.os`,  `device`, etc.) 
   - transaction metrics
   - some of the transaction fields (e.g. `transaction.type`)

- from the span translation branch:
   - mapping of HTTP request / response attributes (e.g. `http.status_code`)
   - network connection info (currently this mapping is on both branches, which looks like a workaround)
   - `service.target` and `destination.resource` fields
   - `span.type` and `span.subtype`
   - destination metrics 

## Solution

To overcome the above limitation, the mobile agents should create a synthetic span that would wrap the outgoing HTTP span, in case they detect that there is no current trace context available at the time of span creation. The wrapper span would then serve as a transaction while the outgoing HTTP span would serve its original role (outgoing client span).

**Comment by LikeTheSalad** [comment]
This is what an orphan http span looks like after this change:

<img width="991" alt="Screenshot 2023-01-30 at 17 21 31" src="https://user-images.githubusercontent.com/56847527/215533806-582f4f6d-230a-4799-8944-12e2adbb12da.png">
