### ISSUE TITLE
Add host.os.version and service.version to span Processor event

### ISSUE THREAD

**Issue by MiriamAparicio** [elastic/apm-agent-android#130]
Currently, when filtering the UI by APP version or OS version there's not `http_requests` returned as we get this from the span processor.event, these fields `host.os.version` and `service.version` are only available in metrics, transactions and errors.

**Comment by LikeTheSalad** [comment]
Related to https://github.com/elastic/apm-server/pull/10697

**Comment by LikeTheSalad** [comment]
This should be no longer an issue after the changes merged [here](https://github.com/elastic/apm-server/pull/10697).
