### ISSUE TITLE
Add possibility to set serverUrl via ElasticApmConfiguration

### ISSUE THREAD

**Issue by ubaierbhat** [elastic/apm-agent-android#176]
Add possiblity to add servicerUrl during ElasticApmAgent initilization. Application can have different servers based on enviorments, flavors etc.

**Comment by LikeTheSalad** [comment]
Hi @ubaierbhat - Thank you for your feedback.

I think you should be able to address this use case by passing a `Connectivity` object with your server endpoint during the ElasticApmAgent initialization like so:

```java
import import co.elastic.apm.android.sdk.connectivity.Connectivity;
//...
String serverUrl = "https://...";
Connectivity myCustomConnectivity = Connectivity.simple(serverUrl); // there are other methods such as Connectivity.withApiKey and Connectivity.withSecretToken in case you need those extra parameters.
ElasticApmAgent.initialize(appContext, myCustomConnectivity);
```

**Comment by LikeTheSalad** [comment]
Good to know it worked! Thanks for your feedback, I believe it's okay to remove the validation in Gradle for the serverUrl as long as we specify in the docs that a runtime exception could happen if it's not set in either place. I've created this issue for it: #182 - I'll close this issue for now, though feel free to reopen it if needed.
