### ISSUE TITLE
Test alerts

### ISSUE THREAD

**Issue by estolfo** [elastic/apm-agent-android#232]
- [x] Should the alerts tab be visible?
- [x] Can alerts be set up for crashes?

**Comment by LikeTheSalad** [comment]
Steps to create alerts for crashes:

### 1.- Go to the Alerts page
![1](https://github.com/elastic/apm-agent-android/assets/56847527/ee1fdf44-b37a-474f-8996-5abb0c881056)

### 2.- Create a new rule
![2](https://github.com/elastic/apm-agent-android/assets/56847527/151cf354-d6b3-4d50-b9cd-1686cbe3dda6)

### 3.- Select "Error count threshold" as the rule type
![3](https://github.com/elastic/apm-agent-android/assets/56847527/89c678c1-0d91-4f52-afd8-a9feaf783239)

### 4.- Enable "Use KQL Filter"
![5 (enable KQL filter)](https://github.com/elastic/apm-agent-android/assets/56847527/ffe3e832-8401-46f1-94a2-fd432e01687d)

### 5.1.- Set it to "all crashes"
![6 1 (all crashes)](https://github.com/elastic/apm-agent-android/assets/56847527/bfd5e195-2430-4ea6-8358-71685636ff52)

### 5.2.- Or set it to "mobile crashes"
![6 2 (mobile crashes)](https://github.com/elastic/apm-agent-android/assets/56847527/f463c468-a6f2-42b7-937e-72c019231d90)

### 5.3.- Or set it to "crashes for a specific app only"
![6 3 (crashes for a single app only)](https://github.com/elastic/apm-agent-android/assets/56847527/78b9efb4-6fa4-45b0-8b93-21c5fd58d4ed)

### 6.1.- Setting up an email alert
![7 1 (setting up email alert)](https://github.com/elastic/apm-agent-android/assets/56847527/9140b681-794b-45b7-b124-30594f6fb347)

### 6.2.- Setting up an email alert (part 2)
![7 2](https://github.com/elastic/apm-agent-android/assets/56847527/7f2cb66b-2e3f-430d-a567-b16117d8e1c5)

### 7.- Success
![8 (finished)](https://github.com/elastic/apm-agent-android/assets/56847527/26bf3fd3-97f0-42ac-ad88-3dd24f4b2aa6)

**Comment by akhileshpok** [comment]
Many thanks @LikeTheSalad!
