### ISSUE TITLE
Add ability to disable apm agent if its not initialized in code

### ISSUE THREAD

**Issue by ubaierbhat** [elastic/apm-agent-android#243]
The logs flooded with 'Configurations have not been initialized.' There should be an option to disable or notify the APM agent that we have intentionally not skipped initialization (e.g., when developing locally or in a staging environment).

**Comment by LikeTheSalad** [comment]
I see, makes sense! The debug logs won't show up on non-debug apps, however, it also seems sensible that the agent shouldn't create any logs if it's not initialized, I'll have a look at it.

**Comment by LikeTheSalad** [comment]
Hi! Some changes were added [here](https://github.com/elastic/apm-agent-android/pull/245) to address this issue and should be available on the next release `0.13.0`.

Thank you for your feedback.
