### ISSUE TITLE
Cause: duplicate entry: LICENSE.txt

### ISSUE THREAD

**Issue by Bekzod1994** [elastic/apm-agent-android#323]
when i add the sdk plugin 

  id("co.elastic.apm.android") version "0.18.0"  

i get this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:debugBytebuddyTransform'.
> Failed to transform classes

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:debugBytebuddyTransform'.
Caused by: org.gradle.api.GradleException: Failed to transform classes
at net.bytebuddy.build.gradle.android.ByteBuddyLocalClassesEnhancerTask.execute(ByteBuddyLocalClassesEnhancerTask.java:21
Caused by: java.util.zip.ZipException: duplicate entry: LICENSE.txt

**Comment by LikeTheSalad** [comment]
Hi @Bekzod1994 

It seems to be an issue with the bytecode instrumentation provided with the Elastic Agent plugin. I'm currently taking a look at it. In the meantime, if you still would like to use the agent without automatic bytecode instrumentation, you could set it up manually, without using the plugin, by following [this guide](https://www.elastic.co/guide/en/apm/agent/android/current/setup.html#manual-setup).

**Comment by Bekzod1994** [comment]
Hi @LikeTheSalad 
  i add it manually but it doesn't work in android library because i have Multi Module project
 
 I read your answer 
 https://github.com/elastic/apm-agent-android/issues/142#issuecomment-1492041003
and am trying to add the plugin in case

**Comment by LikeTheSalad** [comment]
Hi @Bekzod1994 

A new version has been released with a fix for this issue: `0.19.0`. Feel free to reopen this ticket in case you can still see the same error after upgrading.

Thank you for your feedback.

**Comment by mrzbn** [comment]
i am still getting this error:
