### ISSUE TITLE
APM Not Capturing All GET Transactions in Android 11 Environment

### ISSUE THREAD

**Issue by mhutestbyt** [elastic/apm-agent-android#366]
Description:
Dear elastic apm agent android team, I've encountered an issue where the APM agent is not capturing all GET requests as expected. Specifically, when running tests in an Android 11 environment and using MITM tools to observe the network activity, I noticed a discrepancy between the actual GET requests and those captured in Kibana's APM transaction section.

Environment: Android Version: 11
APM Setup: Elastic APM for Android

Steps to Reproduce:

Perform actions within the application that involve multiple GET requests.
Use a MITM tool to monitor network activity.

Expected Behavior as I understood : 
All GET requests should be visible in Kibana's APM transaction section.

Current Behavior:
Only a limited subset of the GET requests appears in the APM transaction logs in Kibana.

Let me know if more details are needed or if there are specific configurations to check for better visibility of these transactions.

Best regards,

**Comment by LikeTheSalad** [comment]
Hi @mhutestbyt - Thank you for your feedback.

To be able to help you properly, I'm going to need the following information:

- Are all of your app's HTTP requests being made with [OkHttp](https://square.github.io/okhttp/) or with a wrapper such as Retrofit?
- Some HTTP spans are standalone, so you'll see them on the APM transactions main section in Kibana, but others are created as children of higher-level transactions, such as an Activity's `onCreate` spans for example, and in those cases, you'd need to open the higher-level span to see the HTTP one inside. In your case, are you trying to find the HTTP spans as standalone only? Or have you looked into other higher-level spans to confirm if they have those HTTP ones as children?
- You mentioned that the environment is Android 11. Have you seen a different behavior in other environments?

Please let me know if you have any questions,

Thanks!
